# $Id$
# Makefile for Windows 32-bit, using Watcom

P_CC = ./tools/owcc.pl
P_RC = true
P_CFLAGS = -b win32 -I$(WATCOM)/h/nt -std=c99
P_LDFLAGS = -b win32
AFTERCMD = wrc -q -i=include -i=$(WATCOM)/h/nt -bt=nt src/fishymail.rc fishymail.exe

include mk/Makefile.windows
